version: 0.1.{build}

before_build:
  - cmd: nuget restore

build_script:
  - ps: .\build.ps1

after_test:
  - cmd: nuget pack .\src\DirectXTexNet\DirectXTexNet.nuspec -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: .\*.nupkg
