version: 0.1.{build}

configuration: Release
platform: x86

before_build:
  - cmd: nuget restore
  - cmd: set
  - cmd: echo {version}
  - cmd: echo {build}

after_test:
  - cmd: nuget pack .\src\DirectXTex.net\DirectXTex.net.nuspec
  
artifacts:
  - path: .\*.nupkg
