version: 0.1.{build}

configuration: Release
platform: x86

before_build:
  - cmd: nuget restore

after_test:
  - cmd: nuget pack .\src\DirectXTex.net\DirectXTex.net.nuspec -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: .\*.nupkg
