version: 0.1.{build}

before_build:
  - cmd: nuget restore

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build_script:
  - ps: .\build.ps1

after_test:
  - cmd: nuget pack .\src\DirectXTexNet\DirectXTexNet.nuspec -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: .\*.nupkg
